#!/bin/bash
if [ -z $1 ];then
	echo "Usage: make-all-blobs <server> [<table name>]"
	exit 1
fi

. /etc/profile.d/mediawiki.sh

server=$1
if [ -z $2 ]; then
	table=blobs
else
	table=$2
fi

if hostname --domain | grep -q wmflabs ; then
	FILE="$MEDIAWIKI_STAGING_DIR/dblists/all-labs.dblist"
else
	FILE="$MEDIAWIKI_STAGING_DIR/dblists/all.dblist"
fi

# Assumes password is the same everywhere
pass=$(echo 'echo $wgDBadminpassword;' | mwscript eval.php --wiki="enwiki");

sqlfile="${PWD%/*/*/*}/maintenance/storage/blobs.sql"

for db in `grep -v '^#' <$FILE`;do
	echo "$db"
	echo "CREATE DATABASE IF NOT EXISTS $db" | mysql -u wikiadmin "-p$pass" -h $server && \
	sed "s/blobs\>/$table/" $sqlfile | mysql -u wikiadmin "-p$pass" -h $server $db
done
